CREATE TABLE `sys`.`Todo_Details` (
  `TASK_ID` BINARY(16) NOT NULL,
  `TITLE` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `IS_COMPLETE` TINYINT(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`TASK_ID`));